const express=require('express')
const playercontroller=require('../controller/player')
const playerMiddelWare=require('../middelware/player')
const adminMiddelWare=require('../middelware/Admin')
const creatorMiddelWare=require('../middelware/creator')
const couponContoller=require('../controller/Coupon')
const router=express.Router()
router.route('/').get(playercontroller.getAll)
router.route('/SignUp').post(playerMiddelWare.CheckEmail,playerMiddelWare.CheckPassword,playerMiddelWare.CheckOther,adminMiddelWare.isAdminExistWhenInsert,creatorMiddelWare.isCreatorExistWhenInsert,playerMiddelWare.isPlayerExistWhenInsert,playercontroller.createPlayer)
router.route('/Login').post(playerMiddelWare.CheckEmail,playerMiddelWare.CheckPassword,playercontroller.LoginPlayer)
router.route('/Ban').post(playercontroller.BanPlayer)
router.route('/player_info').get(playercontroller.Player_info)
router.route('/AddToCart').post(playerMiddelWare.in_cart,playercontroller.add_to_cart)
router.route('/AddToFav').post(playerMiddelWare.in_fav,playercontroller.add_to_fav)
router.route('/ViewCart').post(playercontroller.games_in_cart)
router.route('/RemoveCart').post(playercontroller.remove_from_cart)
router.route('/UseCoupon').post(playercontroller.use_coupon)
router.route('/IsSub').post(playercontroller.is_sub)
router.route('/AddOrder').post(playercontroller.add_order)
router.route('/AddGamesOrder').post(playercontroller.add_game_order,couponContoller.update_coupons)
router.route('/ViewFav').post(playercontroller.games_in_fav)
router.route('/RemoveFav').post(playercontroller.remove_from_fav)
module.exports=router